[tool.poetry]
name = "hello"
version = "0.1.0"
description = "Hello World!"
authors = ["Ja"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
rich = "^12.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
